[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
remappings = [
    "account-factory/=node_modules/modulekit/account-factory/",
    "examples/=node_modules/modulekit/examples/",
    "main/=node_modules/modulekit/main/",
    "modules/=node_modules/modulekit/modules/",
    "safe7579/=node_modules/modulekit/safe7579/",
    "solady/=node_modules/solady/src/",
    "account-abstraction/=node_modules/@ERC4337/account-abstraction/contracts/",
    "account-abstraction-v0.6/=node_modules/@ERC4337/account-abstraction-v0.6/contracts/",
    "sentinellist/=node_modules/sentinellist/src/",
    "forge-std/=node_modules/forge-std/src/",
    "erc7579/=node_modules/erc7579/src/",
    "@safe-global/=node_modules/@safe-global/",
    "erc4337-validation/=node_modules/erc4337-validation/src/",
    "ds-test/=node_modules/ds-test/src/",
    "solmate/=node_modules/solmate/src/",
    "solarray/=node_modules/solarray/src/",
    "checknsignatures/=node_modules/checknsignatures/src/",
    "@ERC4337/=node_modules/modulekit/node_modules/@ERC4337/",
    "@gnosis.pm/=node_modules/modulekit/node_modules/@gnosis.pm/",
    "@openzeppelin/=node_modules/modulekit/node_modules/@openzeppelin/",
    "@prb/=node_modules/modulekit/node_modules/@prb/",
    "hardhat-deploy/=node_modules/modulekit/node_modules/hardhat-deploy/",
    "hardhat/=node_modules/modulekit/node_modules/hardhat/",
    "modulekit/=node_modules/modulekit/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
